
var people=
[
{name: "Mayuri Madhur", description: "Cute, crazy, colorful as daisy.<br>A very dedicated placement coordinator.<br>A qualified swimmer, a good dancer, an artist.<br>She can write some really good stuff as well."},
{name: "Anish Kumar Singh", description: "Very very good person to have around.<br>Very genuine, able, sincere and honest"},
{name: "Pranjal Mohan Saxena", description: "Don't know if anyone called him this but he're really cute. Pranjal will always be remembered for his creative ways to use swear words and unique lifestyle!<br> Pranjal, don't ever let 'em say you're not worth anything good."},
{name: "Abhinav", description: ""},
{name: "Shreya Shambhawi Singh", description: ""},
{name: "Amish Srivastava", description: "A mathematical genius and coding inspiration.<br>His laughter once killed a guy!"},
{name: "Arnav Agyeya", description: "One of the most handsome guys in the batch.<br>Serene, focussed and strong."},
{name: "Ishani Parashar", description: ""},
{name: "Shreya Singh", description: ""},
{name: "Aishwarya Singh", description: ""},
{name: "Rohit Sinha", description: "Don't ever leave that persistent attitude and the soulful apparatus in your hand.<br>We always loved the songs you sang and your company."},
{name: "Prakash Jha", description: "Easy, quiet, humble, simple!"},
{name: "Gaurav Kumar", description: "A very competent vocalist.<br>A great person to have a chat with.<br>Very good at mimicking people!"},
{name: "Hemant Kumar", description: "Mr. Barabanki, sorry but coudn't find much about you!"},
{name: "Nilaya Rakesh", description: "A very talented guy.<br>Expert in multiple musical instruments and a great voice.<br>A very good learner."},
{name: "Vaibhav Pratihar", description: "Humorous, witty, entertaining.<br>The tallest guy in the class."},
{name: "Amit Kumar", description: "Mr. Serious. Mr. Concerned!"},
{name: "Neeraj Sharma (Ji)", description: "There is a reason his name is followed by a 'ji' and it is very serious.<br>As pacific as a sea.<br>Superhumanly humane in this miserable realm."},
{name: "Snehal Kumar", description: "Yeah, this guy is quite like what the picture says! Superman stuff.<br>Genius in coding, academics, being calm and cool, et cetera.<br>Always keen to gain knowledge and work hard."},
{name: "Sheshank Kumar", description: "The first class representative we had.<br>Always ready with his cranky but cute jokes!"},
{name: "Keshav Kumar", description: "The big guy! Commander in coding and mathematics.<br>Humble, smart, adaptive, player, ..."},
{name: "Snehil Kumar", description: "The most decorated dealer in the class.<br>The easiest guy to have a chat with. Curious and serious about photography and society.<br>Anime lover too!"},
{name: "Kumar Sanu", description: "A witty photographer!<br>A Person with a good fashion sense and common sense.<br>The lucky guy! :-P"},
{name: "Pardeshi Babu", description: ""},
{name: "Ansar Hussain", description: "A calculating and manipulative personality.<br>Knows how to influence people with his words.<br>Very quiet and peaceful."},
{name: "Prashant Sahib", description: "Diverging brain and talents :P.<br>He can sing, he can write, he can play.<br>He can sketch, he can code, he can smoke!<br>The most convincing dealer in the class. "},
{name: "Dinesh Sharma", description: "A person with a really unique way of talking.<br>Very talented with a very good set of choices!"},
{name: "Atul Shakya", description: "The man who beat campus placements!<br>Very serious about his work."},
{name: "Ram Babu", description: "Calm, composed, ready to code."},
{name: "Jitendra Kumar Suman", description: "The Gopmandal lookalike!"},
{name: "Vivek Kumar", description: "Always up to do god's own job.<br>Great managerial skills and volunteering instincts for the good of the people."},
{name: "Fareed Subhani", description: "Cute boy!<br>Take care of Sudhanshu! lol."},
{name: "Purushotam Rawatt", description: "An entrepreneur. This guy runs a fucking business serving millions daily.<br>An inspiration.<br>Don't let that cute face fool you!<br>Has a really good fashion sense too!"},
{name: "Keshav Tiwari", description: "Very few people have such simple and elegant lifestyle.<br>Always peaceful and relaxed."},
{name: "Punit Agrawal", description: ""},
{name: "Shubham Singh", description: "A great enthusiast of most domains in computer science!<br>Pretty famous by his nickname, credited to Snehil.<br>Messed up but affectionate."},
{name: "Mithlesh Kumar Singh", description: "One of those guys who wouldn't poke his nose in every other person's business.<br>Plain and effortless man."},
{name: "Priyam Vardhan", description: "The teddy bear!<br>Delusional about his own or someone else's dealing!<br>Always ready to help people.<br>A very sharp brain."},
{name: "Amal Joseph John", description: "The guy who lived his life while others decayed in the gutter of pride!<br>Cheerful and lively."},
{name: "Vikram Nagarjun Singh", description: "The true devdas!<br>Always ready to listen to your sad love story.<br>Hellucinatory about his imaginary world of El Dorado.<br>The final class representative and an extremely good person by heart.<br>He can sing, sketch and play guitar too!"},
{name: "Diksha Singla", description: "'The best girl' in the class.<br>Great placement coordinator and class representative.<br>A very delightful personality."},
{name: "Shiprali Gupta", description: "One of the most ravishing girls in the class.<br>Exceptionally talented in making notes with multicoloured pens!<br>Too sweet."},
{name:"Ravina", description:"The iconic smile!<br>Any young girl who never stops smiling is a 'Ravina' in the making.<br>Someone who truly loved completing every assignment ever given.<br>Ask me, she's the easiest girl in the class to talk to."},
{name:"Kumari Kajal", description:""},
{name:"Vivek Singh", description:"Arguably the most handsome guy, the best coder and the most sincere and hard-working student in academics.<br>Not someone who'd beat the drums crying of his accomplishments.<br>An inspiration."},
{name:"Avinash Singh", description:""}
];